# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4cec598ef988cf68dca47028c9ba053eb9ba0a404a08fe4090a4a15945354492aa97b4e90c2fdaf17261ce9072ea21e7cab682bfa6078f86f4220cfc1927e1a

test:
  secret_key_base: 9325c07e6c39b0b3d53d734d011b8d49fb36d48fa6fd3c776fdbd9607f27bee27ecbda7b2f8f817bd3977cb9105e42e10917e373f972abd195224488c8e663ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
